server:
  port: 8401

spring:
  application:
    name: IMOOD-Monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}


  security:
    user:
      name: imood
      password: 123456