server:
  port: 7001
  servlet:
    context-path: /register

spring:
  application:
    name: IMOOD-Register
  security:
    user:
      name: imood
      password: 123456

  boot:
    admin:
      client:
#        url: http://localhost:8401
        url: http://${imood-monitor-admin}:8401
        username: imood
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
#    hostname: localhost
    hostname: ${imood-register}
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

